# Configuración de proveedores de lenguaje

# Proveedor por defecto
default_provider: openai

# Configuración de proveedores
providers:
  ollama:
    base_url: http://localhost:11434
    default_model: gemma3:1b
  openai:
    api_key: ${OPENAI_API_KEY}
    base_url: https://api.openai.com/v1
    default_model: gpt-3.5-turbo

  claude:
    api_key: ${ANTHROPIC_API_KEY}
    base_url: https://api.anthropic.com/v1
    default_model: claude-3-haiku-20240307

  google_cloud:
    api_key: ${GOOGLE_CLOUD_API_KEY}

# Configuración de red Wi-Fi (opcional)
network:
  ssid: ${WIFI_SSID}
  password: ${WIFI_PASSWORD}